name: Tag

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  id-token: write

jobs:

  lint:
    uses: ./.github/workflows/lint.yml
    secrets: inherit

  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit

  release:
    needs: [lint, test]
    uses: ./.github/workflows/release.yml
    secrets: inherit
